---
name: version
version: 0.81
author:
  - 'John Peacock E<lt>jpeacock@cpan.orgE<gt>'
abstract: Perl extension for Version Objects
license: perl
requires:
  File::Temp: '>= 0.13'
  Test::More: '>= 0.45'
  perl: '> 5.005'
dynamic_config: 1
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
provides:
  version:
    file: lib/version.pm
    version: 0.81
  version::vxs:
    file: vutil/lib/version/vxs.pm
    version: 0.81
resources:
  license: http://dev.perl.org/licenses/
