---
name: version
version: 0.50
author: ~
abstract: ~
license: perl
requires:
  Module::Build: 0.2611
  perl: '> 5.005, !=5.9.1, !=5.9.2'
provides:
  version:
    file: lib/version.pm
    version: 0.50
  version::vxs:
    file: lib/version/vxs.pm
    version: 0.50
generated_by: Module::Build version 0.2611
