---
name: version
version: 0.76_06
author:
  - 'John Peacock E<lt>jpeacock@cpan.orgE<gt>'
abstract: Perl extension for Version Objects
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  perl: '> 5.005'
configure_requires:
  Module::Build: 0.3305
dynamic_config: 1
provides:
  UNIVERSAL:
    file: lib/version.pm
    version: 1.04
  version:
    file: lib/version.pm
    version: 0.76_06
  version::vxs:
    file: vutil/lib/version/vxs.pm
    version: 0.76_06
generated_by: Module::Build version 0.3305
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
