---
name: version
version: 0.59_02
author: ~
abstract: ~
license: perl
requires:
  perl: '> 5.005, < 5.009'
dynamic_config: 1
provides:
  version:
    file: lib/version.pm
    version: 0.59_02
  version::vxs:
    file: vutil/vxs.pm
    version: 0.59_02
generated_by: Module::Build version 0.2611
