---
name: version
version: 0.45
author:
  - John Peacock E<lt>jpeacock@cpan.orgE<gt>
abstract: Perl extension for Version Objects
license: perl
provides:
  version:
    file: lib/version.pm
    version: 0.45
generated_by: Module::Build version 0.2701
