---
name: version
version: 0.83
author:
  - 'John Peacock E<lt>jpeacock@cpan.orgE<gt>'
abstract: Perl extension for Version Objects
license: perl
requires:
  File::Temp: '>= 0.13'
  Test::More: '>= 0.45'
  perl: '> 5.005'
configure_requires:
  Module::Build: 0.340201
dynamic_config: 1
generated_by: Module::Build version 0.340201
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
provides:
  version:
    file: lib/version.pm
    version: 0.83
  version::vxs:
    file: vutil/lib/version/vxs.pm
    version: 0.83
resources:
  license: http://dev.perl.org/licenses/
