---
name: version
version: 0.60
author: ~
abstract: ~
license: perl
requires:
  perl: '> 5.005, < 5.009'
dynamic_config: 1
provides:
  version:
    file: lib/version.pm
    version: 0.60
  version::vxs:
    file: vutil/vxs.pm
    version: 0.60
generated_by: Module::Build version 0.2611
